* WcatOS
猫(1010)がマイペースにちまちま作ってるOS

* 使用しているツール
clangとLLD,Qemuに関してはManjaroLinuxで開発している関係上、バージョンが変わるかもしれません。
- EDK2
- clang version 11.0.0
- LLD 11.0.0 (compatible with GNU linkers)
- QEMU emulator version 5.2.0

* 開発環境
** WcatOSのクローンとEDK2のセットアップ
WcatOSをクローンする(--recursiveを忘れないように!)
SSH keyを登録している場合
#+begin_src shell
git clone git@github.com:No000/WcatOS.git --recursive
#+end_src

していない場合
#+begin_src shell
git clone https://github.com/No000/WcatOS.git --recursive
#+end_src
するとWcatOSディレクトリができる。

次に、tool/edk2/に移動し、以下のコマンドを叩く
#+BEGIN_SRC shell
make -C BaseTools/Source/C
#+END_SRC
以上でセットアップ完了である。

** OVMFのビルド
WcatOSディレクトリ内で
#+begin_src bash
make setup
#+end_src
ビルドが完了すれば、WcatOS/tool/OVMF/に生成されている。

** WcatOSのビルドの準備
WcatOSディレクトリ内で
#+BEGIN_SRC shell
make all
#+END_SRC
すればビルドと実行が行われ、Qemuが起動します。

** ブランチに関して
developがQemuテストで、masterがthinkpad X230による実機テストを行ったものとなります。

* 参考文献
- [[https://github.com/uchan-nos/mikanos][MikanOS]]
- [[http://yuma.ohgami.jp/][大神　祐真さんの自作OS関連の資料]]
- [[https://github.com/Totsugekitai/minOS][minOS]]

* ToDOリスト
- [ ] ASCIIコードの記号を追加実装。
- [ ] GOPの情報を毎回引数で渡さなくて言いようにする。(gSTの使用)
- [ ] print_string関数の実装。
- [X] source edksetup.shを自動化する。 (https://github.com/No000/WcatOS/issues/10)
- [X] OVMFのビルドと配置を自動化する。
- [ ] multiboot2の構造体のみを参考にし、カーネルに渡す情報を整理する。
- [ ] 既存の処理しすてむはmikanos用に移動させる。
- [ ] menu.cとsmbios.cを作成する。
- [ ] マルチスレッドの情報とACPIの情報の吸い出しにトライ
- [ ] 最新のedk2の変更に対応させる

