* フォント
  最初はFT2をくみこめたらいいと考えたが、調べてみると依存関係がかなり大きかった。よって色々調べた結果、以下のようなフォントの実装の仕方を知ることができた。
** SDLのフォントから移植する
   SDLにはhariboteOSのfont.txtのようなビットマップフォントが配列で定義されている。よって、レンダラーを書き換えるだけで容易に移植することができると考えることができる。
*** リンク
	- [[http://nurd.se/~noname/?section=sdl_picofont][sdl_picofont]]
	- [[https://www.libsdl.org/download-2.0.php][SDL2.0から見たい場合はSDL_test_font.c内にある]]
** Scalable Screen Font 2.0を利用する
   FT2上に構築された、依存がとてつもなく少ないフォントレンダラー。.sfnをレンダリングしてくれるそう。
*** .sfnを.oに変換する方法
**** ldかld.lldを使う場合
   #+BEGIN_SRC sh
   ld.lld -r -b binary -m elf_x86_64 -o FreeSerifB.o FreeSerifB.sfn
   #+END_SRC
   これで変換ができる。

*** 組み込む際
	最小限のビットマップフォント等の場合は、メモリ管理機能は必要ない。しかし、全機能を使う場合は必要となる。（一部制限があるも全機能をメモリ機能なしでも使用は頑張ればできるっぽい）
**** リンク
	 - [[https://wiki.osdev.org/Scalable_Screen_Font][OSdev.org[Scalable_Screen_Font]​]]
	 - [[https://gitlab.com/bztsrc/scalable-font2/-/tree/master][Scalable Screen Font 2.0]]
*** .sfnファイルはどうやって組み込む？
	ブートローダーで組み込んだり、objcopyで.oファイルにし、リンクする方法があるっぽい。
**** リンク
	 - [[https://forum.osdev.org/viewtopic.php?t=36711][OSdev.org-viewtopic[How do I load a .sfn font into my kernel?]​]]
*** コード記載する際の注意
	#includeの前で定数を定義しなければならない。
	#+BEGIN_SRC C
	#define SSFN_CONSOLEBITMAP_HICOLOR /* use the special renderer for hicolor     \
                                      packed pixels */
	#define NULL (void *)0
    #include "scalable-font2/ssfn.h"
    extern unsigned char _binary_FreeSerifB_sfn_start;
	#+END_SRC
	
	動かなかったが、とちゅうまで書いたコードを以下にメモする。
	#+BEGIN_SRC C
	ssfn_src = (uint8_t *)&_binary_FreeSerifB_sfn_start;      /* the bitmapfont to use */

    ssfn_dst.ptr = video_infomation->frame_buffer_addr;                  /* address of the linear frame buffer */
    ssfn_dst.w = video_infomation->pixel_per_scanline; /* width */
    ssfn_dst.h = video_infomation->vertical_size;                           /* height */
    ssfn_dst.p = video_infomation->pixel_per_scanline; /* bytes per line */
    ssfn_dst.x = ssfn_dst.y = 0;             /* pen position */
    ssfn_dst.fg = 0xFFFFFFFF;                /* foreground color */
    ssfn_dst.bg = 0xFF000000;                /* background color */
    ssfn_putc(0x41);
    #+END_SRC

** HariboteOSのフォントを移植
   TotsugekitaiさんのminOSv2のコードが参考となる
*** リンク
	- [[https://github.com/Totsugekitai/minOSv2][minOSv2]]

** 大神さんのフォントを移植する
   サンプルコードがあり、移植しやすい。

*** リンク
	[[https://github.com/cupnes/x86_64_jisaku_os_samples/blob/master/022_font/font.c][x86_64_jisaku_os_samples/022_font/font.c]]

* 現状

** ASCII
   確実に動作するフォントとして、大神さんのフォントを移植した。また、ASCIIコードには足りないフォントは自身で作成する。
   特殊文字に関しては、switch文を利用して実装をする。

